train:
  _target_: src.datasets.VAEDataset
  name: "train"
sub_train:
  _target_: src.datasets.VAEDataset
  name: "sub_train"
val:
  _target_: src.datasets.VAEDataset
  name: "val"
viz:
  _target_: src.datasets.VAEDataset
  name: "viz"
