device: "auto"
train:
  - _target_: src.metrics.BlockTypeAccuracy
    name: "BlockTypeAccuracy"
  - _target_: src.metrics.AP
    name: "AirAP"
  - _target_: src.metrics.AttributeAccuracy
    name: "AttributeAccuracy"
  - _target_: src.metrics.AttributeAccuracy
    name: "RawAttributeAccuracy"
    block_equality: False
  - _target_: src.metrics.MaxMemoryAllocated
    name: MaxMemoryAllocated
inference:
  - _target_: src.metrics.BlockTypeAccuracy
    name: "BlockTypeAccuracy"
  - _target_: src.metrics.AP
    name: "AirAP"
  - _target_: src.metrics.AttributeAccuracy
    name: "AttributeAccuracy"
  - _target_: src.metrics.AttributeAccuracy
    name: "RawAttributeAccuracy"
    block_equality: False
