_target_: src.model.DCAE
channels: 192
z_channels: 32
num_layers: 3 # f8
num_res_blocks: 2
attn_layers: []
use_pred_masks: False
posterior_mode: null
additional_norm_layers: True
use_attribute_encoder: True
detach_attribute_decoder: False
use_attribute_decoder_neck: False
