defaults:
  - model: vae
  - metrics: vae
  - datasets: vae_eval # we do not want to run inference on training data
  - dataloader: vae
  - transforms: vae
  - _self_
inferencer:
  device_tensors: ["block_type_grid", "attributes_masks", "attributes_values"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
